# Site settings
name: Supersonic Framework
title:
email: your-email@domain.com
description: "The official AppGyver site"
baseurl: ""
url: "http://www.appgyver.com"
exclude: ['README.md', 'deploy']

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty